# General
name: Leonard Lamprecht
description: A teenagers view on web development and intuitive UI design.
url: https://leo.im
google_verify: WfHNxUaAd-tBjGYLYIJfhHp4x4mCPkeSZedrHjDjgxo

author:
    name: Leonard Lamprecht
    email: lamprechtleonard@gmail.com
    uri: https://leo.im/about/

# Build
markdown: kramdown
kramdown:
    input: GFM
sass:
    style: :expanded

#Other
permalink: /notes/:title
timezone: Europe/Berlin
include: [ 'robots.txt' ]
exclude: [ 'LICENSE', 'README.md', 'CNAME', 'vendor', 'Gemfile' ]
gems:
    - jekyll-sitemap
    - jekyll-feed

# Self explaining
defaults:
  -
    scope:
      path: ""
    values:
      layout: "null"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"